# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chiose',
            new_name='Chioce',
        ),
    ]
