# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160716_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qustion',
            new_name='question',
        ),
    ]
